[package]
name = "phantomos-sys"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
with_builtin_macros = "0.0.3"
bitflags = "2.0.0-rc.1"