#define OK 0
#define PERMISSION -1
#define INVALID_HANDLE -2
#define INVALID_MEMORY -3
#define BUSY -4
#define INVALID_OPERATION -5
#define INVALID_STRING -6
#define INSUFFICIENT_LENGTH -7

#define TIMEOUT -100
#define INTERRUPTED -101

#define UNSUPPORTED_OPERATION -200
#define PENDING -203
